.\" Copyright 2008 Petter Reinholdtsen
.\" May be distributed under the GNU General Public License
.TH "update-bootsystem-insserv" "8" "5 January 2008" "Petter Reinholdtsen" ""
.SH "NAME"
update\-rc.d\-insserv \- insert init.d scripts into boot system using dependency information in the init.d scripts
.SH "DESCRIPTION"
.B update\-rc.d\-insserv
is an implementation of the update-rc.d interface for the dependency
based boot sequencing system insserv.  It is enabled using
update-bootsystem-insserv.
.SH "SEE ALSO"
update\-rc.d(8), insserv(8), update-bootsystem-insserv(8)
.SH "AUTHOR"
Petter Reinholdtsen, <pere@hungry.com>
